### ISSUE TITLE
First run using docker-compose and image v0.20.0 fails

### ISSUE THREAD

**Issue by alcaprar** [gramps-project/Gramps.js#200]
Hello I just tried to run the [docker-compose.yml](https://raw.githubusercontent.com/gramps-project/web/main/examples/docker-compose-base/docker-compose.yml) linked in the doc and I am getting this error:

Image version: `v0.20.0`

```
grampsweb_1        | Traceback (most recent call last):
grampsweb_1        |   File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
grampsweb_1        |     return _run_code(code, main_globals, None,
grampsweb_1        |   File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
grampsweb_1        |     exec(code, run_globals)
grampsweb_1        |   File "/usr/local/lib/python3.9/dist-packages/gramps_webapi/__main__.py", line 195, in <module>
grampsweb_1        |     cli(
grampsweb_1        |   File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1130, in __call__
grampsweb_1        |     return self.main(*args, **kwargs)
grampsweb_1        |   File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1055, in main
grampsweb_1        |     rv = self.invoke(ctx)
grampsweb_1        |   File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1657, in invoke
grampsweb_1        |     return _process_result(sub_ctx.command.invoke(sub_ctx))
grampsweb_1        |   File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1654, in invoke
grampsweb_1        |     super().invoke(ctx)
grampsweb_1        |   File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1404, in invoke
grampsweb_1        |     return ctx.invoke(self.callback, **ctx.params)
grampsweb_1        |   File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 760, in invoke
grampsweb_1        |     return __callback(*args, **kwargs)
grampsweb_1        |   File "/usr/local/lib/python3.9/dist-packages/click/decorators.py", line 26, in new_func
grampsweb_1        |     return f(get_current_context(), *args, **kwargs)
grampsweb_1        |   File "/usr/local/lib/python3.9/dist-packages/gramps_webapi/__main__.py", line 127, in search
grampsweb_1        |     dbmgr = WebDbManager(name=app.config["TREE"], create_if_missing=False)
grampsweb_1        |   File "/usr/local/lib/python3.9/dist-packages/gramps_webapi/dbmanager.py", line 68, in __init__
grampsweb_1        |     self.path = self._get_path()
grampsweb_1        |   File "/usr/local/lib/python3.9/dist-packages/gramps_webapi/dbmanager.py", line 106, in _get_path
grampsweb_1        |     raise ValueError(
grampsweb_1        | ValueError: Database path 'cc7db28e-46e4-4105-8a18-efbd158f0d9d'for family tree 'Gramps Web' not found in database directory /root/.gramps/grampsdb
```

Edit: I just tried to use `v0.19.0` and it worked perfectly.

**Comment by DavidMStraub** [comment]
Thanks, I think it's the same as this https://github.com/gramps-project/gramps-webapi/issues/356
