### ISSUE TITLE
Can't add an existing tree from Gramps to Gramps Web

### ISSUE THREAD

**Issue by Vdauphin** [gramps-project/Gramps.js#202]
Hello,

# Info
I am running Gramps Web in a docker after following this guide https://gramps-project.github.io/web/Deployment/#step-1-docker-configuration. I am using this [.yml](https://github.com/Vdauphin/caprover-one-click-apps/blob/master/public/v4/apps/grampsweb.yml) to make it available as a One Click app in [CapRover](https://caprover.com/)

# Issue

I can't add an existing tree from Gramps to Gramps Web because the web interface doesn't allow me to select a source person. It is weird because in the Gramps app, I already selected the home person

# Description
- I upload to my server the database of my tree from Gramps named `Arbre AGM`
- In the container `gramps -l` show me as detected
```sh
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
List of known Family Trees in your database path

/root/.gramps/grampsdb/3f302c7f-3051-4f5c-8f5f-8eda0829de6e with name "arbre"
/root/.gramps/grampsdb/63a19b9e with name "Arbre AGM"
/root/.gramps/grampsdb/0000c156-d911-4511-94c4-97447abb793d with name "Gramps Web"
/root/.gramps/grampsdb/1c916159-c184-4735-a898-6900e113bb7c with name "Gramps Web 2"
```
- Then I set the name of the tree in Gramps Web:
```yml
GRAMPSWEB_TREE=Arbre AGM
GRAMPSWEB_CELERY_CONFIG__broker_url=redis://srv-captain--notrearbre-redis:6379/0
GRAMPSWEB_CELERY_CONFIG__result_backend=redis://srv-captain--notrearbre-redis:6379/0
GRAMPSWEB_RATELIMIT_STORAGE_URI=redis://srv-captain--notrearbre-redis:6379/1
```
- I am stuck on this page:

![image](https://user-images.githubusercontent.com/14364400/232589251-05aa941e-3585-43c2-832b-fdee0582914a.png)
![image](https://user-images.githubusercontent.com/14364400/232589366-56125341-e09c-45df-b1fe-0a7b3e7d7892.png)

There is no way to select the home person

# Log
<details><summary>grampsweb:v0.20.1</summary>
<p>

```log
2023-04-17T19:13:39.167961811Z INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
2023-04-17T19:13:39.168013432Z INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
2023-04-17T19:13:39.706882457Z [2023-04-17 19:13:39 +0000] [12] [INFO] Starting gunicorn 20.1.0
2023-04-17T19:13:39.707364994Z [2023-04-17 19:13:39 +0000] [12] [INFO] Listening at: http://0.0.0.0:5000 (12)
2023-04-17T19:13:39.707420683Z [2023-04-17 19:13:39 +0000] [12] [INFO] Using worker: sync
2023-04-17T19:13:39.709710228Z [2023-04-17 19:13:39 +0000] [13] [INFO] Booting worker with pid: 13
2023-04-17T19:13:39.766662337Z [2023-04-17 19:13:39 +0000] [14] [INFO] Booting worker with pid: 14
2023-04-17T19:13:39.842071705Z [2023-04-17 19:13:39 +0000] [15] [INFO] Booting worker with pid: 15
2023-04-17T19:13:39.851182768Z [2023-04-17 19:13:39 +0000] [16] [INFO] Booting worker with pid: 16
2023-04-17T19:13:39.934470702Z [2023-04-17 19:13:39 +0000] [18] [INFO] Booting worker with pid: 18
2023-04-17T19:13:39.952017500Z [2023-04-17 19:13:39 +0000] [19] [INFO] Booting worker with pid: 19
2023-04-17T19:13:39.970192407Z [2023-04-17 19:13:39 +0000] [21] [INFO] Booting worker with pid: 21
2023-04-17T19:13:40.023930919Z [2023-04-17 19:13:40 +0000] [22] [INFO] Booting worker with pid: 22
2023-04-17T19:14:56.564817432Z INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
2023-04-17T19:14:56.564865152Z INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
2023-04-17T19:14:57.105686059Z [2023-04-17 19:14:57 +0000] [13] [INFO] Starting gunicorn 20.1.0
2023-04-17T19:14:57.106158208Z [2023-04-17 19:14:57 +0000] [13] [INFO] Listening at: http://0.0.0.0:5000 (13)
2023-04-17T19:14:57.106176494Z [2023-04-17 19:14:57 +0000] [13] [INFO] Using worker: sync
2023-04-17T19:14:57.109439561Z [2023-04-17 19:14:57 +0000] [14] [INFO] Booting worker with pid: 14
2023-04-17T19:14:57.152494359Z [2023-04-17 19:14:57 +0000] [15] [INFO] Booting worker with pid: 15
2023-04-17T19:14:57.159022725Z [2023-04-17 19:14:57 +0000] [16] [INFO] Booting worker with pid: 16
2023-04-17T19:14:57.198797286Z [2023-04-17 19:14:57 +0000] [17] [INFO] Booting worker with pid: 17
2023-04-17T19:14:57.241675796Z [2023-04-17 19:14:57 +0000] [18] [INFO] Booting worker with pid: 18
2023-04-17T19:14:57.308907696Z [2023-04-17 19:14:57 +0000] [19] [INFO] Booting worker with pid: 19
2023-04-17T19:14:57.376780711Z [2023-04-17 19:14:57 +0000] [23] [INFO] Booting worker with pid: 23
2023-04-17T19:14:57.387746640Z [2023-04-17 19:14:57 +0000] [24] [INFO] Booting worker with pid: 24
2023-04-17T19:16:17.129217080Z Unable to init server: Could not connect: Connection refused
2023-04-17T19:16:17.152557564Z Unable to init server: Could not connect: Connection refused
```
</p>
</details>

<details><summary>grampscelery</summary>
<p>

```log
2023-04-15T21:13:56.044233272Z INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
2023-04-15T21:13:56.044332475Z INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
2023-04-15T21:13:56.630413515Z [2023-04-15 21:13:56 +0000] [13] [INFO] Starting gunicorn 20.1.0
2023-04-15T21:13:56.630936818Z [2023-04-15 21:13:56 +0000] [13] [INFO] Listening at: http://0.0.0.0:5000 (13)
2023-04-15T21:13:56.630982548Z [2023-04-15 21:13:56 +0000] [13] [INFO] Using worker: sync
2023-04-15T21:13:56.633376821Z [2023-04-15 21:13:56 +0000] [14] [INFO] Booting worker with pid: 14
2023-04-15T21:13:56.730314336Z [2023-04-15 21:13:56 +0000] [15] [INFO] Booting worker with pid: 15
2023-04-15T21:13:56.803754401Z [2023-04-15 21:13:56 +0000] [16] [INFO] Booting worker with pid: 16
2023-04-15T21:13:56.896882984Z [2023-04-15 21:13:56 +0000] [18] [INFO] Booting worker with pid: 18
2023-04-15T21:13:56.989049434Z [2023-04-15 21:13:56 +0000] [20] [INFO] Booting worker with pid: 20
2023-04-15T21:13:57.001957376Z [2023-04-15 21:13:57 +0000] [22] [INFO] Booting worker with pid: 22
2023-04-15T21:13:57.034055330Z [2023-04-15 21:13:57 +0000] [23] [INFO] Booting worker with pid: 23
2023-04-15T21:13:57.073423629Z [2023-04-15 21:13:57 +0000] [24] [INFO] Booting worker with pid: 24
```
</p>
</details>

<details><summary>redis:7.0.10-alpine</summary>
<p>

```log
2023-04-15T21:28:45.142791069Z 1:C 15 Apr 2023 21:28:45.142 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
2023-04-15T21:28:45.142848506Z 1:C 15 Apr 2023 21:28:45.142 # Redis version=7.0.10, bits=64, commit=00000000, modified=0, pid=1, just started
2023-04-15T21:28:45.142861343Z 1:C 15 Apr 2023 21:28:45.142 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
2023-04-15T21:28:45.143579531Z 1:M 15 Apr 2023 21:28:45.143 * monotonic clock: POSIX clock_gettime
2023-04-15T21:28:45.144724431Z 1:M 15 Apr 2023 21:28:45.144 * Running mode=standalone, port=6379.
2023-04-15T21:28:45.144743211Z 1:M 15 Apr 2023 21:28:45.144 # Server initialized
2023-04-15T21:28:45.144759147Z 1:M 15 Apr 2023 21:28:45.144 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
2023-04-15T21:28:45.145283981Z 1:M 15 Apr 2023 21:28:45.145 * Ready to accept connections
2023-04-15T22:28:46.098376748Z 1:M 15 Apr 2023 22:28:46.098 * 1 changes in 3600 seconds. Saving...
2023-04-15T22:28:46.099111370Z 1:M 15 Apr 2023 22:28:46.098 * Background saving started by pid 15
2023-04-15T22:28:46.174761705Z 15:C 15 Apr 2023 22:28:46.174 * DB saved on disk
2023-04-15T22:28:46.175678925Z 15:C 15 Apr 2023 22:28:46.175 * Fork CoW for RDB: current 0 MB, peak 0 MB, average 0 MB
2023-04-15T22:28:46.199814752Z 1:M 15 Apr 2023 22:28:46.199 * Background saving terminated with success
2023-04-15T23:28:47.075723287Z 1:M 15 Apr 2023 23:28:47.075 * 1 changes in 3600 seconds. Saving...
2023-04-15T23:28:47.076376619Z 1:M 15 Apr 2023 23:28:47.076 * Background saving started by pid 16
2023-04-15T23:28:47.160460655Z 16:C 15 Apr 2023 23:28:47.160 * DB saved on disk
2023-04-15T23:28:47.161294360Z 16:C 15 Apr 2023 23:28:47.161 * Fork CoW for RDB: current 0 MB, peak 0 MB, average 0 MB
2023-04-15T23:28:47.176955249Z 1:M 15 Apr 2023 23:28:47.176 * Background saving terminated with success
2023-04-16T09:39:36.977239952Z 1:M 16 Apr 2023 09:39:36.976 * 1 changes in 3600 seconds. Saving...
2023-04-16T09:39:36.979728396Z 1:M 16 Apr 2023 09:39:36.979 * Background saving started by pid 17
2023-04-16T09:39:37.094463349Z 17:C 16 Apr 2023 09:39:37.094 * DB saved on disk
2023-04-16T09:39:37.095215932Z 17:C 16 Apr 2023 09:39:37.095 * Fork CoW for RDB: current 0 MB, peak 0 MB, average 0 MB
2023-04-16T09:39:37.180894128Z 1:M 16 Apr 2023 09:39:37.180 * Background saving terminated with success
2023-04-16T21:04:13.180221475Z 1:M 16 Apr 2023 21:04:13.179 * 1 changes in 3600 seconds. Saving...
2023-04-16T21:04:13.198584370Z 1:M 16 Apr 2023 21:04:13.180 * Background saving started by pid 18
2023-04-16T21:04:13.433173551Z 18:C 16 Apr 2023 21:04:13.432 * DB saved on disk
2023-04-16T21:04:13.434077738Z 18:C 16 Apr 2023 21:04:13.433 * Fork CoW for RDB: current 0 MB, peak 0 MB, average 0 MB
2023-04-16T21:04:13.482385684Z 1:M 16 Apr 2023 21:04:13.482 * Background saving terminated with success
2023-04-16T22:21:46.408453653Z 1:M 16 Apr 2023 22:21:46.408 * 1 changes in 3600 seconds. Saving...
2023-04-16T22:21:46.409162352Z 1:M 16 Apr 2023 22:21:46.408 * Background saving started by pid 19
2023-04-16T22:21:46.453267868Z 19:C 16 Apr 2023 22:21:46.452 * DB saved on disk
2023-04-16T22:21:46.454086626Z 19:C 16 Apr 2023 22:21:46.453 * Fork CoW for RDB: current 0 MB, peak 0 MB, average 0 MB
2023-04-16T22:21:46.509829958Z 1:M 16 Apr 2023 22:21:46.509 * Background saving terminated with success
2023-04-16T23:21:47.028133187Z 1:M 16 Apr 2023 23:21:47.027 * 1 changes in 3600 seconds. Saving...
2023-04-16T23:21:47.028728650Z 1:M 16 Apr 2023 23:21:47.028 * Background saving started by pid 20
2023-04-16T23:21:47.103500674Z 20:C 16 Apr 2023 23:21:47.103 * DB saved on disk
2023-04-16T23:21:47.104368696Z 20:C 16 Apr 2023 23:21:47.104 * Fork CoW for RDB: current 0 MB, peak 0 MB, average 0 MB
2023-04-16T23:21:47.129401564Z 1:M 16 Apr 2023 23:21:47.129 * Background saving terminated with success
2023-04-17T12:44:19.570149485Z 1:M 17 Apr 2023 12:44:19.569 * 1 changes in 3600 seconds. Saving...
2023-04-17T12:44:19.606329585Z 1:M 17 Apr 2023 12:44:19.570 * Background saving started by pid 21
2023-04-17T12:44:19.648711807Z 21:C 17 Apr 2023 12:44:19.648 * DB saved on disk
2023-04-17T12:44:19.649034667Z 21:C 17 Apr 2023 12:44:19.648 * Fork CoW for RDB: current 0 MB, peak 0 MB, average 0 MB
2023-04-17T12:44:19.671220748Z 1:M 17 Apr 2023 12:44:19.670 * Background saving terminated with success
2023-04-17T17:52:20.570376728Z 1:M 17 Apr 2023 17:52:20.570 * 1 changes in 3600 seconds. Saving...
2023-04-17T17:52:20.570854596Z 1:M 17 Apr 2023 17:52:20.570 * Background saving started by pid 22
2023-04-17T17:52:20.820355298Z 22:C 17 Apr 2023 17:52:20.820 * DB saved on disk
2023-04-17T17:52:20.821230880Z 22:C 17 Apr 2023 17:52:20.820 * Fork CoW for RDB: current 0 MB, peak 0 MB, average 0 MB
2023-04-17T17:52:20.872418023Z 1:M 17 Apr 2023 17:52:20.872 * Background saving terminated with success
2023-04-17T18:52:21.026236097Z 1:M 17 Apr 2023 18:52:21.025 * 1 changes in 3600 seconds. Saving...
2023-04-17T18:52:21.026693499Z 1:M 17 Apr 2023 18:52:21.026 * Background saving started by pid 23
2023-04-17T18:52:21.096226989Z 23:C 17 Apr 2023 18:52:21.095 * DB saved on disk
2023-04-17T18:52:21.097050708Z 23:C 17 Apr 2023 18:52:21.096 * Fork CoW for RDB: current 0 MB, peak 0 MB, average 0 MB
2023-04-17T18:52:21.127360100Z 1:M 17 Apr 2023 18:52:21.127 * Background saving terminated with success
```
</p>
</details>

**Comment by Vdauphin** [comment]
How can I do that? Any command exemple?

**Comment by DavidMStraub** [comment]
What's also weird is that your celery log says i's starting gunicorn, that doesn't make sense, I think something is wrongly set up there, but I am not familiar with this yml service format.

**Comment by Vdauphin** [comment]
Thank you for your fast reply 

```py
root@f6c47f41c928:/app/config# python3 -m gramps_webapi --config /app/config/config.cfg search index-full
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.9/dist-packages/gramps_webapi/__main__.py", line 195, in <module>
    cli(
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1654, in invoke
    super().invoke(ctx)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/gramps_webapi/__main__.py", line 54, in cli
    ctx.obj = {"app": create_app()}
  File "/usr/local/lib/python3.9/dist-packages/gramps_webapi/app.py", line 108, in create_app
    raise ValueError(f"{option} must be specified")
ValueError: SECRET_KEY must be specified
```
If I understand I need to generate secret key with this https://gramps-project.github.io/web/Configuration/#required-settings ?

**Comment by Vdauphin** [comment]
> What's also weird is that your celery log says i's starting gunicorn, that doesn't make sense, I think something is wrongly set up there,

May be I did something wrong

>  but I am not familiar with this yml service format.

It is mostly the original docker-compose.yml with some decoration (https://github.com/caprover/one-click-apps#how-to-create-a-one-click-app-as-of-v180)

**Comment by Vdauphin** [comment]
Oh good news 
```pyroot@94d0e214fe44:/app# python3 -m gramps_webapi search index-full
INFO:gramps_webapi:Rebuilding search index ...
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
INFO:gramps_webapi:Done building search index.
```
And now it works 
![image](https://user-images.githubusercontent.com/14364400/232601090-ffb0c8db-23e1-4efb-960f-a53c59ff23fa.png)
:rocket:

**Comment by DavidMStraub** [comment]
See e.g. [here]() - it is crucial to override the `command` in the celery service with `command: celery -A gramps_webapi.celery worker --loglevel=INFO` instead of gunicorn

**Comment by Vdauphin** [comment]
New to docker here
If I understand  you think the `command` here:  https://github.com/Vdauphin/caprover-one-click-apps/blob/master/public/v4/apps/grampsweb.yml#L49 is not executed?

**Comment by DavidMStraub** [comment]
Hi, that's what it looks like, but not sure since I am not familiar with Caprover. By the way, if/once you get it to work, it would be great to have a 1-click-app and add it as an option to https://gramps-project.github.io/web/ and https://github.com/gramps-project/web/tree/main/examples.

**Comment by Vdauphin** [comment]
> Hi, that's what it looks like,

I see, I need to handle it. It has been done here for redis: https://github.com/caprover/one-click-apps/blob/843cdbfb74477f52f5231c8082c5af82ca0505a6/public/v4/apps/redis.yml#L10-L12
But I don't know what I should use for the `FROM`
```yml
dockerfileLines:
    - FROM dmstraub/gramps:5.1.5
    - CMD exec celery -A gramps_webapi.celery worker --loglevel=INFO
```

> By the way, if/once you get it to work, it would be great to have a 1-click-app and add it as an option to https://gramps-project.github.io/web/ and https://github.com/gramps-project/web/tree/main/examples.

Yes sure, I plan to share my CapRover repository so it will be available directly in the app store for people. I can't add it to the main CapRover repository as it has a low number of download

![image](https://user-images.githubusercontent.com/14364400/232860428-2d89c46f-dbb3-4352-a7c4-a486defdb813.png)

**Comment by Vdauphin** [comment]
I made this change https://github.com/Vdauphin/caprover-one-click-apps/pull/2/files
but gunicorn is still starting:
https://github.com/Vdauphin/caprover-one-click-apps/pull/2#issuecomment-1513738202

Do you have a log file exemple from gramps-celery?

I saw in the main CapRover repo this app doing something similar to Gramps Web: https://github.com/caprover/one-click-apps/blob/e73765dbe92853c49d13f0b15c6dcbb1e22e3a9c/public/v4/apps/saleor.yml#L45-L47
But no much clue

**Comment by DavidMStraub** [comment]
```
grampsweb_celery    |  -------------- celery@d728ee0271e3 v5.2.7 (dawn-chorus)
grampsweb_celery    | --- ***** ----- 
grampsweb_celery    | -- ******* ---- Linux-5.10.103-v8+-aarch64-with-glibc2.31 2023-04-11 07:22:59
grampsweb_celery    | - *** --- * --- 
grampsweb_celery    | - ** ---------- [config]
grampsweb_celery    | - ** ---------- .> app:         default:0xeff2a268 (.default.Loader)
grampsweb_celery    | - ** ---------- .> transport:   redis://grampsweb_redis:6379/0
grampsweb_celery    | - ** ---------- .> results:     redis://grampsweb_redis:6379/0
grampsweb_celery    | - *** --- * --- .> concurrency: 4 (prefork)
grampsweb_celery    | -- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
grampsweb_celery    | --- ***** ----- 
grampsweb_celery    |  -------------- [queues]
grampsweb_celery    |                 .> celery           exchange=celery(direct) key=celery
grampsweb_celery    |                 
grampsweb_celery    | 
grampsweb_celery    | [tasks]
grampsweb_celery    |   . gramps_webapi.api.tasks.export_db
grampsweb_celery    |   . gramps_webapi.api.tasks.import_file
grampsweb_celery    |   . gramps_webapi.api.tasks.search_reindex_full
grampsweb_celery    |   . gramps_webapi.api.tasks.search_reindex_incremental
grampsweb_celery    |   . gramps_webapi.api.tasks.send_email_confirm_email
grampsweb_celery    |   . gramps_webapi.api.tasks.send_email_new_user
grampsweb_celery    |   . gramps_webapi.api.tasks.send_email_reset_password
grampsweb_celery    | 
grampsweb_celery    | [2023-04-11 07:23:00,044: INFO/MainProcess] Connected to redis://grampsweb_redis:6379/0
grampsweb_celery    | [2023-04-11 07:23:00,060: INFO/MainProcess] mingle: searching for neighbors
grampsweb_celery    | [2023-04-11 07:23:01,115: INFO/MainProcess] mingle: all alone
grampsweb_celery    | [2023-04-11 07:23:01,203: INFO/MainProcess] celery@d728ee0271e3 ready.
```

**Comment by Vdauphin** [comment]
Closing as fixed!
