### ISSUE TITLE
Media objects fail to load with error 500

### ISSUE THREAD

**Issue by githubNutzer89** [gramps-project/Gramps.js#260]
Hi,

I tried to set up gramps web by importing my database which worked without trouble. Now I tried also to import my media. Therefore I did the database integrity check which doesn't discover any issues. I took my media folder and turned it into a zip. The upload failed with error 500. The logs show this:

2023-08-10T15:33:33.232346545Z [2023-08-10 15:33:33 +0000] [25] [ERROR] Error handling request /api/media/archive/upload/zip
2023-08-10T15:33:33.233078346Z Traceback (most recent call last):
2023-08-10T15:33:33.233175985Z   File "/usr/local/lib/python3.9/dist-packages/gunicorn/workers/sync.py", line 135, in handle
2023-08-10T15:33:33.233265700Z     self.handle_request(listener, req, client, addr)
2023-08-10T15:33:33.233325563Z   File "/usr/local/lib/python3.9/dist-packages/gunicorn/workers/sync.py", line 178, in handle_request
2023-08-10T15:33:33.233388602Z     respiter = self.wsgi(environ, resp.start_response)
2023-08-10T15:33:33.233450903Z   File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2213, in __call__
2023-08-10T15:33:33.233513967Z     return self.wsgi_app(environ, start_response)
2023-08-10T15:33:33.233569893Z   File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2193, in wsgi_app
2023-08-10T15:33:33.233629932Z     response = self.handle_exception(e)
2023-08-10T15:33:33.233686283Z   File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2190, in wsgi_app
2023-08-10T15:33:33.233848561Z     response = self.full_dispatch_request()
2023-08-10T15:33:33.233920325Z   File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1486, in full_dispatch_request
2023-08-10T15:33:33.233992701Z     rv = self.handle_user_exception(e)
2023-08-10T15:33:33.234057827Z   File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1484, in full_dispatch_request
2023-08-10T15:33:33.234132841Z     rv = self.dispatch_request()
2023-08-10T15:33:33.234200855Z   File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1469, in dispatch_request
2023-08-10T15:33:33.234430559Z     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-08-10T15:33:33.234509323Z   File "/usr/local/lib/python3.9/dist-packages/gramps_webapi/api/auth.py", line 44, in wrapper
2023-08-10T15:33:33.234585912Z     return func(*args, **kwargs)
2023-08-10T15:33:33.234653676Z   File "/usr/local/lib/python3.9/dist-packages/flask/views.py", line 109, in view
2023-08-10T15:33:33.234739003Z     return current_app.ensure_sync(self.dispatch_request)(**kwargs)
2023-08-10T15:33:33.234807804Z   File "/usr/local/lib/python3.9/dist-packages/flask/views.py", line 190, in dispatch_request
2023-08-10T15:33:33.234881231Z     return current_app.ensure_sync(meth)(**kwargs)
2023-08-10T15:33:33.234946307Z   File "/usr/local/lib/python3.9/dist-packages/gramps_webapi/api/resources/import_media.py", line 67, in post
2023-08-10T15:33:33.235021921Z     task = run_task(
2023-08-10T15:33:33.235076297Z   File "/usr/local/lib/python3.9/dist-packages/gramps_webapi/api/tasks.py", line 51, in run_task
2023-08-10T15:33:33.235149986Z     return task(**kwargs)
2023-08-10T15:33:33.235212337Z   File "/usr/local/lib/python3.9/dist-packages/celery/local.py", line 182, in __call__
2023-08-10T15:33:33.235289163Z     return self._get_current_object()(*a, **kw)
2023-08-10T15:33:33.235471842Z   File "/usr/local/lib/python3.9/dist-packages/gramps_webapi/util/celery.py", line 18, in __call__
2023-08-10T15:33:33.235547656Z     return self.run(*args, **kwargs)
2023-08-10T15:33:33.235614470Z   File "/usr/local/lib/python3.9/dist-packages/gramps_webapi/api/tasks.py", line 212, in import_media_archive
2023-08-10T15:33:33.235690871Z     result = run_import_media_archive(
2023-08-10T15:33:33.235762610Z   File "/usr/local/lib/python3.9/dist-packages/gramps_webapi/api/resources/util.py", line 1283, in run_import_media_archive
2023-08-10T15:33:33.235837836Z     check_quota_media(to_add=upload_size, tree=tree)
2023-08-10T15:33:33.235907075Z   File "/usr/local/lib/python3.9/dist-packages/gramps_webapi/api/media.py", line 349, in check_quota_media
2023-08-10T15:33:33.235980789Z     update_usage_media(tree=tree)
2023-08-10T15:33:33.236055378Z   File "/usr/local/lib/python3.9/dist-packages/gramps_webapi/api/media.py", line 338, in update_usage_media
2023-08-10T15:33:33.236129379Z     usage_media = media_handler.get_media_size()
2023-08-10T15:33:33.236182568Z   File "/usr/local/lib/python3.9/dist-packages/gramps_webapi/api/media.py", line 150, in get_media_size
2023-08-10T15:33:33.236255644Z     db_handle = get_db_handle()
2023-08-10T15:33:33.236319808Z   File "/usr/local/lib/python3.9/dist-packages/gramps_webapi/api/util.py", line 167, in get_db_handle
2023-08-10T15:33:33.236391884Z     view_private = has_permissions({PERM_VIEW_PRIVATE})
2023-08-10T15:33:33.236456936Z   File "/usr/local/lib/python3.9/dist-packages/gramps_webapi/api/auth.py", line 79, in has_permissions
2023-08-10T15:33:33.236535850Z     claims = get_jwt()
2023-08-10T15:33:33.236603876Z   File "/usr/local/lib/python3.9/dist-packages/flask_jwt_extended/utils.py", line 29, in get_jwt
2023-08-10T15:33:33.236678052Z     raise RuntimeError(
2023-08-10T15:33:33.236761004Z RuntimeError: You must call `@jwt_required()` or `verify_jwt_in_request()` before using this method

What could be the issue? Am I doing something wrong?

Thanks for your help.

**Comment by DavidMStraub** [comment]
Hi, can you go to settings -> system information and paste the info there? This looks like https://github.com/gramps-project/gramps-webapi/issues/397 which is already fixed.

**Comment by githubNutzer89** [comment]
Gramps 5.1.5
Gramps Web API 1.1.10
Gramps.js 23.8.1
locale: en
multi-tree: false
task queue: false

**Comment by DavidMStraub** [comment]
Ok thanks, looks like a separate bug.
