### ISSUE TITLE
Menu topic "reports" generates error 504

### ISSUE THREAD

**Issue by hartenthaler** [gramps-project/Gramps.js#300]
When selecting the last menu topic "Reports" an 504 error occures.

**Comment by DavidMStraub** [comment]
Interesting. I think this might be related to the following log message

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/gunicorn/workers/sync.py", line 135, in handle
    self.handle_request(listener, req, client, addr)
  File "/usr/local/lib/python3.9/dist-packages/gunicorn/workers/sync.py", line 178, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1478, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1458, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/usr/local/lib/python3.9/dist-packages/gramps_webapi/api/auth.py", line 44, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/flask/views.py", line 109, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
  File "/usr/local/lib/python3.9/dist-packages/flask/views.py", line 190, in dispatch_request
    return current_app.ensure_sync(meth)(**kwargs)
  File "/usr/local/lib/python3.9/dist-packages/webargs/core.py", line 649, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/gramps_webapi/api/resources/reports.py", line 55, in get
    check_fix_default_person(get_db_handle(readonly=False))
  File "/usr/local/lib/python3.9/dist-packages/gramps_webapi/api/util.py", line 330, in get_db_handle
    db_write = get_db_outside_request(
  File "/usr/local/lib/python3.9/dist-packages/gramps_webapi/api/util.py", line 281, in get_db_outside_request
    dbstate = dbmgr.get_db(readonly=readonly)
  File "/usr/local/lib/python3.9/dist-packages/gramps_webapi/dbmanager.py", line 172, in get_db
    smgr.open_activate(
  File "/usr/local/lib/python3.9/dist-packages/gramps_webapi/dbloader.py", line 111, in open_activate
    check_lock(dir_name=filename, mode=mode)
  File "/usr/local/lib/python3.9/dist-packages/gramps_webapi/dbloader.py", line 52, in check_lock
    raise DbLockedError(_("The database is locked."))
gramps_webapi.dbloader.DbLockedError: The database is locked.
```

It looks like under some circumstances the Gramps lock file interferes. I think we should rewrite the `open_activate` method to not even write a lock file...

**Comment by DavidMStraub** [comment]
In this case shifting to the backend :slightly_smiling_face:
