### ISSUE TITLE
Deleting Enclosing parent causes 500 error on children

### ISSUE THREAD

**Issue by andrewvaughan** [gramps-project/Gramps.js#339]
If you delete a Place that is registered as the "Enclosing" parent, it causes all references to any children to throw a 500 error, including maps, etc:

```
gramps-app | [2023-12-26 21:22:32 +0000] [24] [ERROR] Error handling request /api/places/?gramps_id=P0000&backlinks=true&extend=all&locale=en&profile=all
gramps-app | Traceback (most recent call last):
gramps-app |   File "/usr/local/lib/python3.11/dist-packages/gunicorn/workers/sync.py", line 135, in handle
gramps-app |     self.handle_request(listener, req, client, addr)
gramps-app |   File "/usr/local/lib/python3.11/dist-packages/gunicorn/workers/sync.py", line 178, in handle_request
gramps-app |     respiter = self.wsgi(environ, resp.start_response)
gramps-app |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gramps-app |   File "/usr/local/lib/python3.11/dist-packages/flask/app.py", line 1478, in __call__
gramps-app |     return self.wsgi_app(environ, start_response)
gramps-app |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gramps-app |   File "/usr/local/lib/python3.11/dist-packages/flask/app.py", line 1458, in wsgi_app
gramps-app |     response = self.handle_exception(e)
gramps-app |                ^^^^^^^^^^^^^^^^^^^^^^^^
gramps-app |   File "/usr/local/lib/python3.11/dist-packages/flask/app.py", line 1455, in wsgi_app
gramps-app |     response = self.full_dispatch_request()
gramps-app |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gramps-app |   File "/usr/local/lib/python3.11/dist-packages/flask/app.py", line 869, in full_dispatch_request
gramps-app |     rv = self.handle_user_exception(e)
gramps-app |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gramps-app |   File "/usr/local/lib/python3.11/dist-packages/flask/app.py", line 867, in full_dispatch_request
gramps-app |     rv = self.dispatch_request()
gramps-app |          ^^^^^^^^^^^^^^^^^^^^^^^
gramps-app |   File "/usr/local/lib/python3.11/dist-packages/flask/app.py", line 852, in dispatch_request
gramps-app |     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
gramps-app |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gramps-app |   File "/usr/local/lib/python3.11/dist-packages/gramps_webapi/api/auth.py", line 44, in wrapper
gramps-app |     return func(*args, **kwargs)
gramps-app |            ^^^^^^^^^^^^^^^^^^^^^
gramps-app |   File "/usr/local/lib/python3.11/dist-packages/flask/views.py", line 109, in view
gramps-app |     return current_app.ensure_sync(self.dispatch_request)(**kwargs)
gramps-app |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gramps-app |   File "/usr/local/lib/python3.11/dist-packages/flask/views.py", line 190, in dispatch_request
gramps-app |     return current_app.ensure_sync(meth)(**kwargs)
gramps-app |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gramps-app |   File "/usr/local/lib/python3.11/dist-packages/webargs/core.py", line 649, in wrapper
gramps-app |     return func(*args, **kwargs)
gramps-app |            ^^^^^^^^^^^^^^^^^^^^^
gramps-app |   File "/usr/local/lib/python3.11/dist-packages/gramps_webapi/api/resources/base.py", line 387, in get
gramps-app |     200, [self.full_object(obj, args, locale=locale)], args, total_items=1
gramps-app |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gramps-app |   File "/usr/local/lib/python3.11/dist-packages/gramps_webapi/api/resources/base.py", line 91, in full_object
gramps-app |     obj = self.object_extend(obj, args, locale=locale)
gramps-app |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gramps-app |   File "/usr/local/lib/python3.11/dist-packages/gramps_webapi/api/resources/places.py", line 48, in object_extend
gramps-app |     obj.profile = get_place_profile_for_object(
gramps-app |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gramps-app |   File "/usr/local/lib/python3.11/dist-packages/gramps_webapi/api/resources/util.py", line 361, in get_place_profile_for_object
gramps-app |     _place = db_handle.get_place_from_handle(handle)
gramps-app |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gramps-app |   File "/usr/lib/python3/dist-packages/gramps/gen/db/generic.py", line 1285, in get_place_from_handle
gramps-app |     return self._get_from_handle(PLACE_KEY, Place, handle)
gramps-app |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gramps-app |   File "/usr/lib/python3/dist-packages/gramps/gen/db/generic.py", line 1270, in _get_from_handle
gramps-app |     raise HandleError('Handle %s not found' % handle)
gramps-app | gramps.gen.errors.HandleError: Handle f7e8f271b09468cc754718a7255 not found
```

**Comment by andrewvaughan** [comment]
Discussion on Gramps board, as well, if this is an issue there: https://gramps-project.org/bugs/view.php?id=13115

**Comment by DavidMStraub** [comment]
Thanks for reporting this bug. In general, it's better not to post it in multiple places. In particular, I would recommend not to open a bug you encountered in Gramps Web in the Gramps bug tracker until it has been confirmed that the bug affects Gramps core. More often than not, the bug is in a component that is special to Gramps Web.

I'll move this to the backend repository.
