### ISSUE TITLE
ValueError: TREE must be specified

### ISSUE THREAD

**Issue by lamanux** [gramps-project/Gramps.js#81]
When I run :

`docker-compose up -d`

I get this Traceback :

```
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.9/dist-packages/gramps_webapi/__main__.py", line 130, in <module>
    cli(
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1654, in invoke
    super().invoke(ctx)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/gramps_webapi/__main__.py", line 43, in cli
    ctx.obj = create_app()
  File "/usr/local/lib/python3.9/dist-packages/gramps_webapi/app.py", line 61, in create_app
    raise ValueError("TREE must be specified")
ValueError: TREE must be specified
```

**Comment by DavidMStraub** [comment]
Yes, you're right, I also just bumped into that. With the new Web API version, in principle you can start without a tree and upload it during onboarding, however when updating the documentation I forgot that the TREE variable is still required and one also needs to create an empty database, which is currently not done in the default docker image. I'll try to fix that, since having the simpler setup without a need to create a database manually would be much better...

**Comment by DavidMStraub** [comment]
Fixed in [Web API 0.4.1](https://github.com/gramps-project/gramps-webapi/releases/tag/v0.4.1).

**Comment by ulysses4ever** [comment]
I redownloaded the docker image, but it seems to fail with the same old error...

```shell
❯ cat docker-compose.yml
version: "3.7"

services:
  grampsweb:
    image: ghcr.io/gramps-project/grampsweb:latest
    restart: always
    ports:
      - "5000:5000"  # host:docker
    volumes:
      - /home/artem/data/gramps/gramps_users:/app/users  # persist user database
      - /home/artem/data/gramps/gramps_index:/app/indexdir  # persist search index
      - /home/artem/data/gramps/gramps_thumb_cache:/app/thumbnail_cache  # persist thumbnails
      - /home/artem/data/gramps/gramps_secret:/app/secret/secret  # persist flask secret
      - /home/artem/data/gramps/gramps_db:/root/.gramps/grampsdb  # persist Gramps database
      - /home/artem/data/gramps/gramps_media:/app/media  # persist media files

❯ sudo docker-compose up -d                                                                             0 (3.490s) < 02:52:02
Pulling grampsweb (ghcr.io/gramps-project/grampsweb:latest)...
latest: Pulling from gramps-project/grampsweb
0c6b8ff8c37e: Pull complete
82b7ff08d0b7: Pull complete
50d41ecbe72c: Pull complete
b2a3f29f14a0: Pull complete
1a7ec717e098: Pull complete
db1c7687af9a: Pull complete
342b07eb0b40: Pull complete
d7ad4cbc6e13: Pull complete
f4a86df4c04b: Pull complete
55958b40bbd0: Pull complete
44e11a6fa01b: Pull complete
15d2fe4cae41: Pull complete
4f4fb700ef54: Pull complete
0bdc93bbb76c: Pull complete
bc5c8909741e: Pull complete
b83d294e37cb: Pull complete
967aa4bf6a8a: Pull complete
304e059e4379: Pull complete
0b4821950467: Pull complete
Digest: sha256:c55978f8e45cfeda24cd805a441372672d13130e4ea2257b0554e39c855cbb76
Status: Downloaded newer image for ghcr.io/gramps-project/grampsweb:latest
Creating gramps_grampsweb_1 ... done

❯ sudo docker images                                                                                    0 (0.002s) < 03:00:07
REPOSITORY                         TAG            IMAGE ID       CREATED         SIZE
ghcr.io/gramps-project/grampsweb   latest         e8ac1325afbe   5 hours ago     1.72GB

❯ sudo docker ps                                                                                       0 (31.258s) < 02:52:39
CONTAINER ID   IMAGE                                     COMMAND                  CREATED         STATUS                          PORTS     NAMES
ebc36ee80a8a   ghcr.io/gramps-project/grampsweb:latest   "/docker-entrypoint.…"   2 minutes ago   Restarting (1) 14 seconds ago             gramps_grampsweb_1

❯ sudo docker-compose logs grampsweb                                                                    1 (1.520s) < 02:56:37
Attaching to gramps_grampsweb_1
grampsweb_1  | cat: /app/secret/secret: Is a directory
grampsweb_1  | Traceback (most recent call last):
grampsweb_1  |   File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
grampsweb_1  |     return _run_code(code, main_globals, None,
grampsweb_1  |   File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
grampsweb_1  |     exec(code, run_globals)
grampsweb_1  |   File "/usr/local/lib/python3.9/dist-packages/gramps_webapi/__main__.py", line 130, in <module>
grampsweb_1  |     cli(
grampsweb_1  |   File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1130, in __call__
grampsweb_1  |     return self.main(*args, **kwargs)
grampsweb_1  |   File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1055, in main
grampsweb_1  |     rv = self.invoke(ctx)
grampsweb_1  |   File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1654, in invoke
grampsweb_1  |     super().invoke(ctx)
grampsweb_1  |   File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1404, in invoke
grampsweb_1  |     return ctx.invoke(self.callback, **ctx.params)
grampsweb_1  |   File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 760, in invoke
grampsweb_1  |     return __callback(*args, **kwargs)
grampsweb_1  |   File "/usr/local/lib/python3.9/dist-packages/click/decorators.py", line 26, in new_func
grampsweb_1  |     return f(get_current_context(), *args, **kwargs)
grampsweb_1  |   File "/usr/local/lib/python3.9/dist-packages/gramps_webapi/__main__.py", line 43, in cli
grampsweb_1  |     ctx.obj = create_app()
grampsweb_1  |   File "/usr/local/lib/python3.9/dist-packages/gramps_webapi/app.py", line 61, in create_app
grampsweb_1  |     raise ValueError("TREE must be specified")
grampsweb_1  | ValueError: TREE must be specified
```

Notice how it says:
```
Digest: sha256:c55978f8e45cfeda24cd805a441372672d13130e4ea2257b0554e39c855cbb76
```
That's exactly the last image [as per GH registry](https://github.com/gramps-project/Gramps.js/pkgs/container/grampsweb).

**Comment by DavidMStraub** [comment]
This is intentional. Please see the updated docs. You need to set the TREE environment variable.

**Comment by ulysses4ever** [comment]
Thank you, that worked.
